# ~/ilab-infrastructure/ansible/group_vars/all.yaml

# Identity Settings
admin_user: "jthairu"
admin_group: "jthairu"
admin_uid: 1000
admin_gid: 1000

# timezone
timezone: "America/New_York"

# NAS login
nas_ip: "10.10.10.95"
nas_user: "jthairu"
nas_pass: "Mucii1311254*#"

# mounts to NAS
storage_mounts:
  - { path: '/volume1/downloads', share: 'downloads' }
  - { path: '/volume1/music', share: 'music' }
  - { path: '/volume1/video', share: 'video' }

# Base paths
app_data_root: "/opt/media-stack"
nas_root: "/volume1"

# Specific share paths (matching the storage_mounts)
download_path: "{{ nas_root }}/downloads"
music_path: "{{ nas_root }}/music"
video_path: "{{ nas_root }}/video"

# Logging
loki_url: "http://10.10.10.90:3100/loki/api/v1/push"


# for media apps - use VIP (connects to either haproxy-01 or haproxy-02)
postgres_host: "10.10.10.220" 

# Media Database Config
media_db_pass: "Mucii1311254"