$ANSIBLE_VAULT;1.1;AES256
38303739393930633936376231613766383736353265303339386336303334626264323164636564
3565616362343335363831386538323665396335613330380a653531356530613066613238373566
33333062386465663631663239326136616564353439376565366563326364383338613439663037
6430373837353231630a363738626339396136613832376331643930356163613364653733386639
31333161346531326337363030616332313261633833306666376565316466396530303763656436
62373438626530336234323731346332636161313166613831383236636165386534346435386530
65613837326163366638313933623761303336666233636331326466663363353132663831633236
32393234356535346132316164376563343664383163623939343030653461333537396433616230
61346139366662656163333031373232623632333964353832363032623561393462
