---
- name: Standardize HAProxy Service
  hosts: proxy_nodes
  become: yes
  tasks:
    - name: Create systemd service file for custom HAProxy
      copy:
        dest: /etc/systemd/system/haproxy.service
        content: |
          [Unit]
          Description=HAProxy Load Balancer
          After=network.target

          [Service]
          ExecStartPre=/usr/local/sbin/haproxy -f /usr/local/etc/haproxy/haproxy.cfg -c -q
          ExecStart=/usr/local/sbin/haproxy -W -db -f /usr/local/etc/haproxy/haproxy.cfg
          ExecReload=/usr/local/sbin/haproxy -f /usr/local/etc/haproxy/haproxy.cfg -c -q
          ExecReload=/bin/kill -USR2 $MAINPID
          KillMode=mixed
          Restart=always
          Type=notify

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd to recognize new service
      systemd:
        daemon_reload: yes

    - name: Enable and Start HAProxy service
      systemd:
        name: haproxy
        state: started
        enabled: yes