---
- name: Rolling Restart to apply Static Parameters
  hosts: db_nodes
  become: yes
  serial: 1  # This processes nodes one by one
  
  tasks:
    - name: Restart Patroni
      systemd:
        name: patroni
        state: restarted

    - name: Wait for node to come back online
      uri:
        url: "http://localhost:8008/health"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 30
      delay: 10

    - name: Pause to allow cluster stabilization
      pause:
        seconds: 15