$ANSIBLE_VAULT;1.1;AES256
34333638313036643737616335323032353336383637363766363666383138343432336464636235
6138636463363435303532366135396561373561303465630a356135663362633465646232613534
33653562323766336336616264613132373936346434643638633262373831653137393765663565
6462613663363731340a363531626330613133396533343066646134396364613965636536663934
30336266393764336431353937656430353730396330643639646665616361343061666138613430
38353265656662633230313437623861346166316430306261633438646532646532373264393539
35663437636639336161663266346430626437343038316433613532626463393039346239366664
61323430633161623133636139326563346566323434636131313830316138363062383130663163
30336232613031313531306637303634393232633462366637356666656437373532636435643733
35343336393766393338353533666163633363353763623537393963653765306362376338633939
39396238653466396461626566373238626532633630383131323362393032353435653461343266
65326331353733616361
